### ISSUE TITLE
TASCAM US-16x08 - Executable Binaries / Installable Packages

### ISSUE THREAD

**Issue by ZergeiW72** [onkelDead/tascam-gtk#7]
Hi There ...

Could it be possible for you to provide me with executable binaries for all this TASCAM stuff ?
Especially  tascam-gtk, tascam.lv2 and the tascam-driver-patch

Regards,
non-coder ZergeiW .

**Comment by onkelDead** [comment]
Hi,

sorry, but binaries compiled on my development engine wont help you in any case.
The repos tascam-gtk and tascam.lv2 are intent to be compiled on your own device, to ensure proper operation. No coding expirience is required, just clone them and execute .configure, make and make install.
The driver patch is part of classic linux kernel since version 4.11. You must follow the installation instructions only if you must use it on an earlier kernel version.

Greets,
Onkel

**Comment by ZergeiW72** [comment]
Hi There ...

I know there's this clone / download as Zip - from witch to choose from .

Now ... What does this cloning mean ? Never done a thing like that .
I think I can manage .configure, make and make install, as long as I have c++ or something like that on my system . ... Correct ?

- Toni -

**Comment by rekado** [comment]
You can install tascam-gtk as an executable binary with GNU Guix on all GNU/Linux systems.
